// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjyd4cNAzyHUXC6M_v1Izi7YCo4-0tCjg',
    appId: '1:969330776178:web:d1d609c39b9beb96f38aeb',
    messagingSenderId: '969330776178',
    projectId: 'espacoja-185c4',
    authDomain: 'espacoja-185c4.firebaseapp.com',
    storageBucket: 'espacoja-185c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9j7SSrXC6zPZLd6AWfQWkiItI9E_UZs0',
    appId: '1:969330776178:android:e990952fe25e7a32f38aeb',
    messagingSenderId: '969330776178',
    projectId: 'espacoja-185c4',
    storageBucket: 'espacoja-185c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfr55qi0aPW1E7GSrDGcYRo7zUilhViE',
    appId: '1:969330776178:ios:ba8f4fadc5a1b797f38aeb',
    messagingSenderId: '969330776178',
    projectId: 'espacoja-185c4',
    storageBucket: 'espacoja-185c4.appspot.com',
    iosBundleId: 'com.example.espacoJa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwfr55qi0aPW1E7GSrDGcYRo7zUilhViE',
    appId: '1:969330776178:ios:ba8f4fadc5a1b797f38aeb',
    messagingSenderId: '969330776178',
    projectId: 'espacoja-185c4',
    storageBucket: 'espacoja-185c4.appspot.com',
    iosBundleId: 'com.example.espacoJa',
  );

}